apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns
  namespace: ddns
data:
  CLOUDFLARE_API_TOKEN: REDACTED_BASE64

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: oznu/cloudflare-ddns:latest
          env:
            - name: ZONE
              value: REDACTED
            - name: SUBDOMAIN
              value: REDACTED
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns
                  key: CLOUDFLARE_API_TOKEN
